language: node_js
node_js:
  - "12"
script:
  - yarn run build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 4f3018458df84a7e5d18d4eb5c3bd30cf22f43e6
  keep-history: true
  on:
    branch: master