language: node_js
node_js:
  - "12"
install: npm
cache: npm
script:
  - npm run build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name "ckw"
  - git config --global user.email "${EMAIL}"
  - git add -A
  - git commit -m 'deploy'
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master